### ISSUE TITLE
Complete all unit test in router/mod.rs

### ISSUE THREAD

**Issue by arn-the-long-beard** [arn-the-long-beard/seed-routing#12]
From the very nice checklist made by @Ben-PH , 2 items are left

- [ ]  subscribe

- [x]  confirm_navigation

I am not sure yet on how we can test these 2 functions. It might be not possible to do it yet.

**Comment by arn-the-long-beard** [comment]
I am not sure if we can find a way to test the `subscribe` method.

**Comment by Ben-PH** [comment]
I'm thinking that `subscribe` testing comes under integration testing with `seed` itself. I'm thinking testing it would be within the scope of integrating it into `seed`?

**Comment by arn-the-long-beard** [comment]
Yes it is !!! Then I guess we can close this one.
