### ISSUE TITLE
Add integration tests and (maybe) unit tests for router_macro_derive

### ISSUE THREAD

**Issue by arn-the-long-beard** [arn-the-long-beard/seed-routing#14]
We need to check the tests we already have for `router_macro_derive` 

Checklist of sniff-testing the public Api for `router_macro_derive` 

- [ ] add_router()
This function create a macro that is called on the top of you lib.rs in you Seed application,
It creates a Router using the `enum` `Routes` as a global variable that you can call everywhere in your app.

- [x] derive_as_url()
This function is a derive macro to use on an Enum to add Url & String conversion.

- [x] derive_add_default_route()
This function is a derive macro to use on an Enum to add a default() implementation for a default_route.

- [x] derive_add_module_load()
This function is a derive macro to use on an Enum to add : 
             -  Url & String conversion.
             -  A default() implementation for a default_route
             -  Load other modules and their routes
             -  Add a folder as a sub module

**Comment by arn-the-long-beard** [comment]
I see that `tests` for `add_router()!` is missing.

**Comment by arn-the-long-beard** [comment]
Testing `add_router` with `RoutingModules` and `ParseUrl`,` WithDefaultRoute` should be enough for now.

**Comment by Ben-PH** [comment]
I'm all for closing this issue. Integration testing is gonna be a long-slog, and is an ongoing continuous improvement thing. I think the risk of unintentionally closing it prematurely if testing isn't as comprehensive as it _should_ be right now is much of a problem. In any case, what will be needed for integration testing will become clearer while we bring it into `seed` itself. If anything gets left behind by closing this, we can open another issue that captures the "perpetually needing improvement" notion a bit more explicitly.

**Comment by arn-the-long-beard** [comment]
Yes this make sens actually. I do close it. Thank you for your feedback :+1:
