### ISSUE TITLE
Test `#[derive(RoutingModules)]`

### ISSUE THREAD

**Issue by Ben-PH** [arn-the-long-beard/seed-routing#15]
Unit and Integration testing of procedural macros is not so straight forward, particularly when the correctness depends on the naming and layout of modules such as with `RoutingModules`

default behavior to test:

- [x] matching enum variant names to module names
- [x] correctly calls `init` on UrlChange

attributes to test:
- [x] `as_path` 
- [x] `view`
- [x] `guard`
- [x] `default_route`
- [x] `modules_path`

**Comment by Ben-PH** [comment]
plan to give [compiletest-rs](https://crates.io/crates/compiletest_rs) a go for this

**Comment by arn-the-long-beard** [comment]
Do you think we could use `https://github.com/laumann/compiletest-rs` to make sure that sometime the code used with our attributes is also failing when it should fail ? ( like a path with "/" or path conflict issue )

**Comment by arn-the-long-beard** [comment]
`correctly calls init on UrlChang` I tried to make test for this one. But the issue comes from Orders.

There is no way right now I can make some mockup orders to test the update function for example.

**Comment by arn-the-long-beard** [comment]
Never mind, I found a solution :smile:

**Comment by arn-the-long-beard** [comment]
I close the issue since tests are mostly complete. We could use more combination in the future but for now url payload do work great with `init` , `update` and `view`
