### ISSUE TITLE
[as_path] attribute usage

### ISSUE THREAD

**Issue by arn-the-long-beard** [arn-the-long-beard/seed-routing#17]
Hello :smiley: 

From our discussion with @Ben-PH , we saw inconsistencies with    `#[as_path = ""]`  : 

- Warning triggering  at compile time  "**Unit variant without a name must be declared last.**" seems purely semantic when the enumeration variant is a unit. Removing the warning and changing the position  in the enumeration does not produce any bug.
- When the Route is nested route = when the enumeration variant is an unnamed field like this :  

```rust

#[derive(Debug, PartialEq, Clone, RoutingModules)]
#[modules_path = "pages"]
pub enum Route {
    #[as_path = ""]
    #[guard = " => guard => forbidden"]
    Dashboard(pages::dashboard::Routes), // -> http://localhost:8000/dashboard/*

}
```

We get an error message `cannot move out of *nested which is behind a shared reference` at compile time

- When used on named field, we have an inconsistent behaviour : 
   -> Seems working with  `query: IndexMap<String, String>`

   -> Does not work with `{id: String}` at run time `panicked at 'Should have param id', /home/arnaud/Projects/seed-routing/src/router/url.rs:68:10`
  -> I do not know with only  `{ children: pages::admin::Routes }`

- There is no check if multiple paths are the same. At run time, the routing/navigation become broken and  cannot link to the right route.

We need to discuss the issue and what to expect from   `#[as_path = ""]`  and `as_path` in general. 

Let's make a tiny todo list together, and I will update this first post with it.

- [ ] Check for path conflict in the same enum
- [x] Throw error if "/" is used inside the rename of the path
- [x] Fix bug with `{id: String}` and empty path
- [x] Need to Agree if we enforce empty variant as last or not with `#[as_path = ""]`
- [x] Set compile time error when empty path used on non unit Variant in enum

**Comment by Ben-PH** [comment]
[referenced function](https://github.com/arn-the-long-beard/seed-routing/blob/bd5e769e5926f9657c940e717dd2f0714eaf0ea2/router_macro_derive/src/routing.rs#L12)

From what I can see, This is the entry point to resolving this issue.

Before the fold, we have an iterable that contains information on the routing path. At that point, we can scan them and ensure that 
every path is unique. If we put each routing path into a `HashSet`, we can abort if there already exists an entry.

The problem I see becoming a gargantuan headache is for this issues example. What about this:

```rust
enum ParentRoutes {
    #[as_path = ""]
    Dashboard(pages::db::ChildRoutes),
    #[as_path = "dashboard/conflict_route"]
    ConflictRoute, // -> /dashboard/conflict_route
}
enum ChildRoutes {
    ConflictRoute // -> /dashboard/conflict_route
}
```

I don't know if something like this has already been accounted for or not. With that said, I've been getting the sense that these sort of edge-cases will need to be accounted for.

**Comment by arn-the-long-beard** [comment]
Okay, good point.

I think we should not be able to rename a path with `"/"` inside. So we should have a check for this I guess.


>   If we put each routing path into a HashSet, we can abort if there already exists an entry.
  
I will give it a try.

**Comment by arn-the-long-beard** [comment]
Todo list updated :smile:

**Comment by arn-the-long-beard** [comment]
Can you tell me what do you think about the code for the 2 last commit  ?

0349b6ca45d95abeb202034b825fc9a4caeef8d8

eb2320f50888366883bea22231373f0d83f5a58c


If your review is ok, I validate these items in the todo list, or I make changes.

Good catch for the `HashSet` by the way, It is very handy :+1

**Comment by arn-the-long-beard** [comment]
Okay, I made some thinking. 

Maybe we should not allow empty path on a module and with argument inside the enumeration.

**Comment by Ben-PH** [comment]
I agree with the renaming rule. We can consider adding it as a feature some time, but not from r the time being.

I'm   away from my desk for the time being, but set use looks fine from what I can see.

**Comment by arn-the-long-beard** [comment]
Okay I think I will keep the rule to have empty path a the end for now. The bug with empty path and id does not exist since we do not allow empty path and enum Variant with fields together anymore.
