### ISSUE TITLE
Improve Testing

### ISSUE THREAD

**Issue by arn-the-long-beard** [arn-the-long-beard/seed-routing#2]
We do already have several unit and integration tests but they cover a limited part of `seed_routing` and they lack structure and cases to document the Api.

Here is the todo list of tests we need to write : 

- [x] Move integration-tests from `router/mod.rs` to folder` /tests`  
- [x] Add more unit tests in `router/mod.rs`
- [x] Add Integration test for `RoutingModules` and the methods of implemented traits : `Navigation` , `View`, `Init` and `DefaultRoute` on `tests/routing_modules/mod.rs`
- [x] Add unit test for `router_macro_derive`. Well I am not sure about this one and if there is a way to add unit test for the code 
- [x] Check and Add more integration tests for `router_macro_derive`. We need to check that we do have all the cases.

Is there other tests we need to add regarding seed_routing ?

**Comment by Ben-PH** [comment]
I can start on the integration movement now, then I can start making unit tests.

**Comment by Ben-PH** [comment]
checklist of sniff-testing the public functions in `routing_module/mod.rs`
RouterData<Route>
- [ ] push_to_history
- [ ] is_on_last_index
- [ ] new
- [ ] init
- [ ] subscribe
- [x] back
- [ ] can_back_with_route
- [ ] can_back
- [ ] can_forward
- [ ] can_forward_with_route
- [x] forward
- [ ] is_current_route
- [x] navigate_to_new
- [?] navigate_to_url
- [ ] request_moving_back
- [ ] request_moving_forward
- [ ] confirm_navigation
- [ ] set_current_route
- [ ] current_route
- [ ] default_route
- [ ] base_url
- [ ] current_history_index
- [ ] forward
- [ ] is_current_route
- [ ] navigate_to_new
- [ ] navigate_to_url
- [ ] request_moving_back

**Comment by arn-the-long-beard** [comment]
Thank you for the check !!!. I might have written too many public functions actually. Do you think there is strategies there I could use to simplify ?

**Comment by arn-the-long-beard** [comment]
Well I have just added 

```rust

    #[wasm_bindgen_test]
    fn test_new_router() {
        let router = Router::<ExampleRoutes>::new();
        let current = router.current_route();
        let default = router.default_route();
        let router_data = router.data.borrow();

        assert_eq!(router_data.sub_handle.is_none(), true);
        assert_eq!(router_data.current_history_index, 0);
        assert_eq!(router_data.history.is_empty(), true);
        assert_eq!(router_data.current_move, MoveStatus::Ready);
        assert_eq!(current, default);
    }


```

What do you think about it ?

**Comment by Ben-PH** [comment]
Yeah, looks good.

Don't know about dropping `can_back/forward()` or not. Sure, it's an elaborate way to just check the `Option`, but it could clear up cognitive load for the user: forcing them to use `router.can_back_with_route().is_some()` in the code means they have to parse 2 extra elements of complexity in their mind when they come back to it later.

When I end up using this part of the library, I'll keep it in mind. I think it comes down to "is `can_back/forward()` a usage edge-case?"

**Comment by arn-the-long-beard** [comment]
> Yeah, looks good.
> 
> Don't know about dropping `can_back/forward()` or not. Sure, it's an elaborate way to just check the `Option`, but it could clear up cognitive load for the user: forcing them to use `router.can_back_with_route().is_some()` in the code means they have to parse 2 extra elements of complexity in their mind when they come back to it later.
> 
> When I end up using this part of the library, I'll keep it in mind. I think it comes down to "is `can_back/forward()` a usage edge-case?"

I think we solved this with the last PR right ?

**Comment by arn-the-long-beard** [comment]
I just have added

```rust

    #[wasm_bindgen_test]
    fn test_push_to_history() {
        let router = Router::<ExampleRoutes>::new();
        let route = ExampleRoutes::Dashboard(DashboardRoutes::Profile(23));
        router.push_to_history(route.clone());

        let history = router.map_data(|data| data.history.clone());
        assert_eq!(history.get(0).unwrap(), &route);
    }

    #[wasm_bindgen_test]
    fn test_peek_back() {
        let router = Router::<ExampleRoutes>::new();
        let previous_route = router.peek_back();
        assert_eq!(previous_route.is_none(), true);
        let route_1 = ExampleRoutes::Dashboard(DashboardRoutes::Profile(23));
        router.push_to_history(route_1.clone());
        let route_2 = ExampleRoutes::Login;
        router.push_to_history(route_2);
        let previous_route = router.peek_back().unwrap();
        assert_eq!(previous_route, route_1);
    }

```

**Comment by arn-the-long-beard** [comment]
Well, that is why unit-tests are awesome :smiley: 

I found a bug in how MovingStatus was updated in `request_moving_forward()` and `request_moving_back()`.

The move was updated even if  `peek()` were returning `None` when there were no previous or next route.

**Comment by Ben-PH** [comment]
I've ticked off a few in the comment above. Some functions aren't tested explicitly, but they are essentially "getter methods", and are used in the tests for the less trivial functions. 

just `subscribe`, `confirm_navigation`, and `is_on_last_index`. That last one should be trivial to tick-off.

**Comment by arn-the-long-beard** [comment]
I just have seen that my commit fails the tests. That is logical after our discussion regarding `last_index` :smile:

**Comment by Ben-PH** [comment]
#15 should push things along.

**Comment by arn-the-long-beard** [comment]
I checked the unit test since we do have it as compile time in `tests` folder for now. We could use extra library later on. But we need to have more hands on the library I guess.

**Comment by arn-the-long-beard** [comment]
I close it. We have enough tests for  first release.
