### ISSUE TITLE
example does not compile

### ISSUE THREAD

**Issue by pythoneer** [arn-the-long-beard/seed-routing#23]
Hi @arn-the-long-beard i was about to take a deeper look into your great project. I forked it to explore it bit better and maybe contribute to some extend at least some documentation/examples (i will open another issue for that). Unfortunately the `backbone_app` example does not compile. I am not exactly sure why but it looks like the current seed master has some breaking changes for exporting type paths*¹. I changed the current `seed = { git = "https://github.com/seed-rs/seed.git" }` in the example `Cargo.toml` to `seed="0.8.0"` like you did in the main project and it seems to work.

*¹
```
expected enum `seed::virtual_dom::Node`, found enum `seed::virtual_dom::node::Node`
expected struct `seed::browser::url::Url`, found struct `seed::Url`
impl has extra requirement `impl Orders<Msg>: seed::app::Orders<Msg>`
```

**Comment by arn-the-long-beard** [comment]
Hey, thank you so much  for your message !!! 

I had the same issue and I forgot to make the commit actually :facepalm:  , I just made it happen now .

https://github.com/arn-the-long-beard/seed-routing/commit/e6d2ee1cec0a360505e792d344392e975d4bac49

Thank you for the feedback. I close the issue !
